version: '3.7'

services:

  # init-container
  # generate certifiactes for server and client
  gen-certificates:
    image: mrjoshlab/udp2grpc:latest
    command:
      - "gen-certificates"
      # server ip address
      - "--ip"
      - "127.0.0.1"
      # certificates directory
      - "--dir"
      - "/cert"
    volumes:
      - "$PWD/cert/:/cert"

  # udp2grpc server container
  udp2grpc-server:
    image: mrjoshlab/udp2grpc:latest
    ports:
      - "52935:52935/tcp"
    command:
      - "server"
      # grpc listen address
      - "-l0.0.0.0:52935"
      # remote conn address
      - "-r127.0.0.1:51820"
      # tls certificate public file
      - "--tls-cert-file"
      - "/cert/server.crt"
      # tls certificate pivate file
      - "--tls-key-file"
      - "/cert/server.key"
      # super secure password here
      - "--password=super-secure-password"
    volumes:
      - "$PWD/cert/:/cert"
    restart: unless-stopped
    depends_on:
      gen-certificates:
        condition: service_completed_successfully

  # udp2grpc client container
  udp2grpc-client:
    image: mrjoshlab/udp2grpc:latest
    ports:
      - "51820:51820/udp"
    command:
      - "client"
      # local udp connection address
      - "-l0.0.0.0:51820"
      # server ip address with port
      - "-r127.0.0.1:52935"
      # tls certificate public file
      - "--tls-cert-file"
      - "/cert/server.crt"
      # super secure password here
      - "--password=super-secure-password"
    volumes:
      - "$PWD/cert/server.crt:/cert/server.crt"
    restart: unless-stopped
    depends_on:
      gen-certificates:
        condition: service_completed_successfully
